# Generated by Django 4.1.7 on 2023-03-15 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Blog',
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Blog'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name_plural': 'Settings'},
        ),
    ]
