# Generated by Django 4.1.7 on 2023-03-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='Fname',
        ),
    ]
