# Generated by Django 4.1.7 on 2023-04-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='title_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
