# Generated by Django 4.1.7 on 2023-04-10 10:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_blog_description_alter_blog_description_az_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='title_az',
        ),
        migrations.RemoveField(
            model_name='test',
            name='title_en',
        ),
        migrations.AddField(
            model_name='blog',
            name='description_tr',
            field=ckeditor.fields.RichTextField(blank=True, help_text='for the data', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_tr',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_tr',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
    ]
