# Generated by Django 4.1.7 on 2023-04-25 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_subscriber_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='is_active',
        ),
    ]
