# Generated by Django 4.1.7 on 2023-04-30 08:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_productcategory_product_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description_az',
            field=ckeditor.fields.RichTextField(blank=True, help_text='for the data', null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, help_text='for the data', null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description_tr',
            field=ckeditor.fields.RichTextField(blank=True, help_text='for the data', null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_tr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
