# Generated by Django 4.1.7 on 2023-05-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_coursecategory_level_price_pricecat_time_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='title_two',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
